baseURL = 'http://scuffedbytes.com'
languageCode = 'en-us'
title = 'ScuffedBytes'
theme = 'manis-hugo-theme'

paginate = 10
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
	[[menu.main]]
		name = "Posts"
		url = "/post/"
	
	[[menu.main]]
		name = "About"
		url = "/about"
		
[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# Site meta description
	description = "ScuffedBytes, an independant tech blog."
	# Site's Tagline (Subtitle or Keyword)
	tagline = "It's a bit scuffed"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
	#licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	mainSections = ["blog", "post"]
	# Configure which sections for Latest Works
	workSections = ["work"]

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#ff6565"
	# Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go", "csharp" ]
	highlightJsStyle = "ocean"